# Generated by Django 3.2.7 on 2022-01-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0002_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
