# Generated by Django 3.2.7 on 2022-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0004_auto_20220112_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additems',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additems',
            name='prod_id',
            field=models.IntegerField(unique=True),
        ),
    ]
