# Generated by Django 3.2.7 on 2022-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0005_auto_20220112_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='additems',
            name='flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additems',
            name='offerprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additems',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
