# Generated by Django 3.2.7 on 2022-01-15 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0006_auto_20220112_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchshop',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchshop',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchshop',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
