# Generated by Django 3.2.7 on 2022-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0010_remove_additems_gotocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchshop',
            name='productavailability',
            field=models.IntegerField(default=0),
        ),
    ]
