# Generated by Django 3.2.7 on 2022-03-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0011_merchshop_productavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additems',
            name='city',
        ),
        migrations.RemoveField(
            model_name='additems',
            name='location',
        ),
    ]
