# Generated by Django 3.2.7 on 2022-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0012_auto_20220305_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcatelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=100, unique=True)),
                ('maincategoryname', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
