# Generated by Django 3.2.7 on 2022-03-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchboxapp', '0015_additems_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchshop',
            name='district',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
