# Generated by Django 3.2.7 on 2022-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=250, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartproduct', models.CharField(max_length=200)),
                ('cart', models.IntegerField()),
                ('productid', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('available', models.IntegerField(default=1)),
            ],
        ),
    ]
