# Generated by Django 3.2.7 on 2022-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='gotocart',
            field=models.IntegerField(default=0),
        ),
    ]
