# Generated by Django 3.2.7 on 2022-02-21 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_cartitems_gotocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 4, 37, 8, 80568, tzinfo=utc)),
        ),
    ]
