# Generated by Django 3.2.7 on 2022-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_auto_20220225_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='gotocart',
        ),
    ]
