# Generated by Django 3.2.7 on 2022-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_remove_cartitems_gotocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('housename', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('pin', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('productname', models.CharField(max_length=200)),
                ('shopname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
    ]
