# Generated by Django 3.2.7 on 2022-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0006_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vg', models.IntegerField()),
            ],
        ),
    ]
