# Generated by Django 3.2.7 on 2022-02-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0007_ti'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase',
            new_name='buy',
        ),
    ]
