# Generated by Django 3.2.7 on 2022-02-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0008_rename_purchase_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ti',
        ),
    ]
