# Generated by Django 3.2.7 on 2022-03-27 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0015_alter_buy_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 15, 32, 50, 551871, tzinfo=utc)),
        ),
    ]
