# Generated by Django 3.2.7 on 2022-03-27 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0016_alter_buy_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
