# Generated by Django 3.2.7 on 2022-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0017_alter_buy_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='sellinguser',
            field=models.CharField(default='not given', max_length=200),
        ),
    ]
